package com.combros.vendingmachine.common.base.domain.model

data class InitSetup (
    var vendCode: String,
    var androidId: String,
    var username: String,
    var password: String,
    var portVendingMachine: String,
    var baudRateVendingMachine: String,
    var portCashBox: String,
    var baudRateCashBox: String,
    var typeVendingMachine: String,
    var fullScreenAds: String,
    var withdrawalAllowed: String,
    var autoStartApplication: String,
    var layoutHomeScreen: String,
    var autoTurnOnTurnOffLight: String,
    var timeTurnOnLight: String,
    var timeTurnOffLight: String,
    var autoResetAppEveryday: String,
    var timeResetOnEveryDay: String,
    var dropSensor: String,
    var inchingMode: String,
    var glassHeatingMode: String,
    var highestTempWarning: String,
    var lowestTempWarning: String,
    var temperature: String,
    var initPromotion: String,
    var currentCash: Int,
    var timeoutJumpToBigAdsScreen: String,
    var timeoutPaymentByCash: String,
    var timeoutPaymentByQrCode: String,
    var timeoutRemoveCart: String,
    var timeClosingSession: String,
    var timeStartSession: String,
    var typePaymentOnline: String,
    var numberSlot: Int,
    var role: String,
)